### ISSUE TITLE
Write Up Part 1

### ISSUE THREAD

**Issue by amad-person** [tshradheya/tshradheya.github.io#12]
#### Why Hire Me?

I am extremely passionate about software engineering. I have built quite a few side projects from scratch to learn some of the latest technologies that are being used currently to develop software.

I am currently an active contributor to TEAMMATES and the Wikimedia Commons Application. Working on these two products has given me experience in learning to write enterprise level code and contributing to the open source software movement.

Apart from my technical prowess, I also possess good leadership skills and can work well in a team. I have led several project groups in university and was part of the Head Student Council in my high school.

I also possess good communication skills and have quite some experience in giving Tech Talks. 

Being very determined and committed to achieving my goals, I can be a great asset to any team since I will do my best to get work done.

### Why this internship?

[WIP]

### Typos

- iContacts - Builder Patter
- `this()` should be `this ()`
- `this- ` should be `this -`
- political discussion`s` with strangers

### UI

- Skills bars: Text should be white

**Comment by tshradheya** [comment]
Fixed as of 29th March 1:35 am

Waiting for further review
